### ISSUE TITLE
Would you construct VAE?

### ISSUE THREAD

**Issue by yanoyoshiki** [Issa-N/torch_tutorial_y-i-3#5]
Is your feature request related to a problem? Please describe.

Yes, my feature request is related to a problem. Currently, we are dealing with complex datasets in our projects that could potentially benefit from more sophisticated models. However, we have not yet explored the use of advanced generative models such as Variational Autoencoders (VAEs).

Describe the solution you'd like

I propose that we construct a Variational Autoencoder (VAE) for our tasks. VAEs are a type of generative model that are particularly good at learning latent representations of data, which can be useful for tasks such as anomaly detection, image generation, and more. We could create a generic VAE structure that can be easily adapted to different datasets and tasks.

Describe alternatives you've considered

An alternative solution could be to use simpler models such as traditional autoencoders or PCA for dimensionality reduction and latent space learning. However, VAEs have the advantage of being probabilistic, meaning they can generate diverse outputs, and can also incorporate complex prior knowledge about the latent space.

**Comment by Issa-N** [comment]
OK, I done
