### ISSUE TITLE
Would you constract AE? 

### ISSUE THREAD

**Issue by yanoyoshiki** [Issa-N/torch_tutorial_y-i-3#6]
Is your feature request related to a problem? Please describe.

Yes, my feature request is related to a problem. Currently, we are dealing with high-dimensional data in our projects and are facing challenges in effectively capturing the structure and complexity of this data. We have not yet implemented any dimensionality reduction methods or unsupervised learning techniques that could help us handle this high-dimensional data more effectively.

Describe the solution you'd like

I suggest that we construct an Autoencoder (AE) for our tasks. Autoencoders are a type of neural network that are good at learning compact representations of data, which can be beneficial for tasks such as anomaly detection, noise reduction, and feature extraction. We could create a generic AE structure that can be easily adapted to different datasets and tasks.

Describe alternatives you've considered

An alternative solution could be to use traditional dimensionality reduction methods such as PCA. However, Autoencoders have the advantage of being able to learn non-linear transformations and capture more complex patterns in the data.

**Comment by Issa-N** [comment]
Ok, I done
